
### Get all the messages
GET http://localhost:8080/conta

### Post 'Hello!"
POST http://localhost:8080/conta
Content-Type: application/json

{
  "status": "ok3",
  "valorTotal": 867.25,
  "qdeParcelas": 5,
  "valorParcela": 88.00
}